### ISSUE TITLE
[Feature Request] Change owo to uwu in certain scenarios

### ISSUE THREAD

**Issue by snarkyerica** [Awoolyx/OwO#1]

**Comment by Awoolyx** [comment]
Hi @snarkyerica !

Thanks for your contribution to the disease of OwO!

OwO happens in our DMs, rather than on GitHub - this GitHub repository is a read-nothing mirror that isn't used for accepting contributions. So that your change can become part of OwO, please allow me to paw.

To add, sending patches isn't quite as simple as sending a pull request, but fortunately it is a well documented process.

Here's what to do:

- Format your contribution according to arwwf requirements
- Decide who to send your contribution to
- Set up your system to send your contribution as an email
- Send your contribution and wait for feedback

**Comment by snarkyerica** [comment]
I would like to point out the unending irony in the following image.
<img width="925" alt="image" src="https://user-images.githubusercontent.com/52387455/151295663-6c4ddd44-1cdf-4086-bc7e-dd5bb12aa5e4.png">
